import {
  readdirSync,
  statSync,
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function getFiles(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function getArtifactOfContract(contractName) {
  const current_path_to_artifacts = join(
    __dirname,
    "..",
    `out/${contractName}.sol`
  );
  const artifactPath = join(current_path_to_artifacts, `${contractName}.json`);

  if (!existsSync(artifactPath)) return null;

  const artifactJson = JSON.parse(readFileSync(artifactPath, "utf8"));

  return artifactJson;
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact?.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function readDeploymentFile(filePath) {
  try {
    return JSON.parse(readFileSync(filePath, "utf8"));
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}: ${error.message}`);
    return null;
  }
}

function processDeploymentExports(deploymentsPath) {
  const allContracts = {};
  const deploymentFiles = getFiles(deploymentsPath).filter((file) =>
    file.endsWith(".json")
  );

  deploymentFiles.forEach((deploymentFile) => {
    const chainId = deploymentFile.slice(0, -5);
    const deploymentObject = readDeploymentFile(
      join(deploymentsPath, deploymentFile)
    );

    if (!deploymentObject) return;

    Object.entries(deploymentObject).forEach(([address, contractName]) => {
      if (address === "networkName") return;

      if (typeof contractName !== "string") {
        console.warn(
          `Warning: Skipping deployment entry ${chainId}.${address}; contract name must be a string.`
        );
        return;
      }

      const artifact = getArtifactOfContract(contractName);

      if (!artifact) {
        console.warn(
          `Warning: Missing artifact for ${contractName}; skipping ${address} on chain ${chainId}.`
        );
        return;
      }

      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
      };
    });
  });

  return allContracts;
}

function main() {
  const current_path_to_deployments = join(__dirname, "..", "deployments");

  const allGeneratedContracts = processDeploymentExports(
    current_path_to_deployments
  );

  // Resolve nextjs contracts dir from this package (packages/foundry/scripts-js -> packages/nextjs/contracts)
  const NEXTJS_TARGET_DIR = join(__dirname, "..", "..", "nextjs", "contracts");

  // Ensure target directories exist
  if (!existsSync(NEXTJS_TARGET_DIR)) {
    mkdirSync(NEXTJS_TARGET_DIR, { recursive: true });
  }

  // Generate the deployedContracts content
  const fileContent = Object.entries(allGeneratedContracts).reduce(
    (content, [chainId, chainConfig]) => {
      return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(
        chainConfig,
        null,
        2
      )},`;
    },
    ""
  );

  // Write the files
  const fileTemplate = (importPath) => `
    ${generatedContractComment}
    import { GenericContractsDeclaration } from "${importPath}";

    const deployedContracts = {${fileContent}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;

  writeFileSync(
    join(NEXTJS_TARGET_DIR, "deployedContracts.ts"),
    format(fileTemplate("~~/utils/scaffold-hbar/contract"), {
      parser: "typescript",
    })
  );

  console.log(
    `📝 Updated TypeScript contract definition file on ${join(
      NEXTJS_TARGET_DIR,
      "deployedContracts.ts"
    )}`
  );
}

try {
  main();
} catch (error) {
  console.error("Error:", error);
  process.exitCode = 1;
}
