blank_issues_enabled: true
contact_links:
  - name: Ask Question
    url: https://github.com/buidler-labs/scaffold-hbar/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
  - name: Request Feature
    url: https://github.com/buidler-labs/scaffold-hbar/discussions/new?category=ideas
    about: Request features or brainstorm ideas for new functionality
