/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    ChainlinkPriceOracleAdapter: {
      address: "0x338EA1E4bcc1E0f7dE0694f42d7b98d41D8B7a99",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "feedConfigs",
              type: "tuple[]",
              internalType: "struct ChainlinkPriceOracleAdapter.FeedConfig[]",
              components: [
                {
                  name: "pairKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "feed",
                  type: "address",
                  internalType: "address",
                },
              ],
            },
            {
              name: "maxStaleness_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MAX_STALENESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROVIDER_KEY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getFeed",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "feed",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latestPrice",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "data",
              type: "tuple",
              internalType: "struct IPriceOracle.PriceData",
              components: [
                {
                  name: "pairKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "providerKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "priceE18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "updatedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "error",
          name: "ChainlinkFeedIsZero",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleConfigIsEmpty",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleIncompleteRound",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleInvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "OraclePairAlreadyConfigured",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "OraclePairKeyIsZero",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleStalePrice",
          inputs: [
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxStaleness",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "OracleUnsupportedPair",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
    SupraPriceOracleAdapter: {
      address: "0x4B38b2715d24a51Dc9B79B8F9A31334D5a2660fA",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "supraOracle_",
              type: "address",
              internalType: "address",
            },
            {
              name: "pairConfigs",
              type: "tuple[]",
              internalType: "struct SupraPriceOracleAdapter.PairConfig[]",
              components: [
                {
                  name: "pairKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "supraPairId",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "maxStaleness_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MAX_STALENESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROVIDER_KEY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SUPRA_ORACLE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISupraSValueFeed",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSupraPairId",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "supraPairId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latestPrice",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "data",
              type: "tuple",
              internalType: "struct IPriceOracle.PriceData",
              components: [
                {
                  name: "pairKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "providerKey",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "priceE18",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "updatedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "error",
          name: "OracleConfigIsEmpty",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleIncompleteRound",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleInvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "OraclePairAlreadyConfigured",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "OraclePairKeyIsZero",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleStalePrice",
          inputs: [
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxStaleness",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "OracleUnsupportedPair",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "SupraOracleIsZero",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
    OracleConsumer: {
      address: "0xd183C8ba05d882Df0e6f6F2Db842E8975314bed5",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "oracle_",
              type: "address",
              internalType: "address",
            },
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "baseToQuote",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "baseAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseDecimals",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "quoteDecimals",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "quoteAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oracle",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPriceOracle",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "quoteToBase",
          inputs: [
            {
              name: "pairKey",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "quoteAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "baseDecimals",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "quoteDecimals",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "baseAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setOracle",
          inputs: [
            {
              name: "newOracle",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OracleUpdated",
          inputs: [
            {
              name: "previousOracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleIsZero",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
