/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  296: {
    MemejobDCAFactory: {
      address: "0xfb541c64d5130f976eead6637a977acb386ac01a",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_memejob",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createVault",
          inputs: [],
          outputs: [
            {
              name: "vault",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "memejob",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userVault",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "VaultCreated",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "vault",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "MemejobDCAFactory__AlreadyHasVault",
          inputs: [],
        },
        {
          type: "error",
          name: "MemejobDCAFactory__InvalidMemejob",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 32974435,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
