import * as fs from "fs";
import * as path from "path";

const GENERATED_COMMENT = `/**
 * This file is autogenerated by Scaffold-HBAR cross-chain-dca.
 * You should not edit it manually or your changes might be overwritten.
 */`;

export async function generateDeployedContracts(configDir: string): Promise<void> {
  const deployedPath = path.join(configDir, "deployed-addresses.json");
  if (!fs.existsSync(deployedPath)) {
    console.warn("⚠️  generateDeployedContracts: deployed-addresses.json not found, skipping.");
    return;
  }

  const deployed = JSON.parse(fs.readFileSync(deployedPath, "utf8"));

  const hederaArtifactsDir = path.resolve(__dirname, "../artifacts/contracts/hedera");
  const sepoliaArtifactsDir = path.resolve(__dirname, "../artifacts/contracts/sepolia");

  const hederaContracts = readContracts(hederaArtifactsDir, [
    { name: "DcaOrchestrator", address: deployed.hederaOrchestrator },
    { name: "AxelarMessageSender", address: deployed.hederaMessageSender },
  ]);

  const sepoliaContracts = readContracts(sepoliaArtifactsDir, [
    { name: "DcaExecutor", address: deployed.sepoliaExecutor },
    { name: "AxelarMessageReceiver", address: deployed.sepoliaMessageReceiver },
  ]);

  const targetPath = path.resolve(__dirname, "../../nextjs/contracts/deployedContracts.ts");
  const targetDir = path.dirname(targetPath);

  let existingEntries: Record<string, Record<string, unknown>> = {};
  if (fs.existsSync(targetPath)) {
    try {
      const existing = fs.readFileSync(targetPath, "utf8");
      const match = existing.match(/const deployedContracts\s*=\s*(\{[\s\S]*\})\s*as const/);
      if (match) {
        existingEntries = new Function(`return ${match[1]}`)();
      }
    } catch {
      // If parsing fails, start fresh
    }
  }

  const merged = { ...existingEntries };

  if (Object.keys(hederaContracts).length > 0) {
    merged["296"] = { ...(merged["296"] ?? {}), ...hederaContracts };
  }
  if (Object.keys(sepoliaContracts).length > 0) {
    merged["11155111"] = { ...(merged["11155111"] ?? {}), ...sepoliaContracts };
  }

  const fileContent = Object.entries(merged)
    .map(([chainId, contracts]) => `  ${chainId}: ${JSON.stringify(contracts, null, 4)},`)
    .join("\n");

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  fs.writeFileSync(
    targetPath,
    `${GENERATED_COMMENT}\nimport { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";\n\nconst deployedContracts = {\n${fileContent}\n} as const;\n\nexport default deployedContracts satisfies GenericContractsDeclaration;\n`,
  );

  console.log("📝 Updated deployedContracts.ts");
}

function readContracts(
  artifactsDir: string,
  contracts: { name: string; address: string | undefined }[],
): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const { name, address } of contracts) {
    if (!address) continue;

    const artifactPath = path.join(artifactsDir, `${name}.sol`, `${name}.json`);
    if (!fs.existsSync(artifactPath)) {
      console.warn(`⚠️  Artifact not found for ${name} — run compile first: ${artifactPath}`);
      continue;
    }

    const { abi } = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    result[name] = { address, abi, inheritedFunctions: {} };
  }

  return result;
}
